---

- name: Pre-install | Check swift tool
  command: swift list

- name: Pre-install | Set local facts
  set_fact:
    get_packages: false
    get_binaries: false
    get_containers: false

- name: Pre-install | Get packages list
  when:
    - swift_objects_packages_container is defined
    - swift_objects_packages_container != None
    - swift_objects_packages_container | length > 0
  block:
    - name: Pre-install | Packages - swift list
      register: swift_result
      shell: swift list {{ swift_objects_packages_container }} || true

    - name: Pre-install | Packages - Set local fact
      when: swift_result.stdout_lines | length > 0
      set_fact:
        get_packages: true
        packages_list: "{{ swift_result.stdout_lines }}"

- name: Pre-install | Get binaries list
  when:
    - swift_objects_binaries_container is defined
    - swift_objects_binaries_container != None
    - swift_objects_binaries_container | length > 0
  block:
    - name: Pre-install | Binaries - swift list
      register: swift_result
      shell: swift list {{ swift_objects_binaries_container }} || true

    - name: Pre-install | Binaries - Set local fact
      when: swift_result.stdout_lines | length > 0
      set_fact:
        get_binaries: true
        binaries_list: "{{ swift_result.stdout_lines }}"

- name: Pre-install | Get containers list
  when:
    - swift_objects_oci_repo_container is defined
    - swift_objects_oci_repo_container != None
    - swift_objects_oci_repo_container | length > 0
  block:
    - name: Pre-install | Containers - swift list
      register: swift_result
      shell: >
        swift list {{ swift_objects_oci_repo_container }} \
        | awk '/index.json/ {print $1}'

    - name: Pre-install | Containers - Set local fact
      when: swift_result.stdout_lines | length > 0
      set_fact:
        get_containers: true
        containers_list: "{{ swift_result.stdout_lines }}"
